import {
  FaGithub,
  FaLinkedin,
  FaEnvelope,
  FaTwitter,
  FaFigma,
  FaMobileAlt,
  FaCode,
  FaCreditCard,
  FaUserFriends,
  FaGlobe,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNodeJs,
  FaGitAlt,
  FaBootstrap,
  FaDatabase,
  FaLaptopCode,
  FaTerminal,
  FaWindows,
  FaBolt,
} from "react-icons/fa";

export const Icon = {
  gitIcon: <FaGithub />,
  linkedInIcon: <FaLinkedin />,
  emailIcon: <FaEnvelope />,
  twitterIcon: <FaTwitter />,
  figmaIcon: <FaFigma />,
  mobileIcon: <FaMobileAlt />,
  codeIcon: <FaCode />,
  creditCardIcon: <FaCreditCard />,
  userFriendsIcon: <FaUserFriends />,
  globeIcon: <FaGlobe />,
  htmlIcon: <FaHtml5 />,
  cssIcon: <FaCss3Alt />,
  jsIcon: <FaJs />,
  reactIcon: <FaReact />,
  nodeIcon: <FaNodeJs />,
  gitAltIcon: <FaGitAlt />,
  bootstrapIcon: <FaBootstrap />,
  mysqlIcon: <FaDatabase />,
  mongodbIcon: <FaDatabase />,
  expressIcon: <FaTerminal />,
  javaIcon: <FaLaptopCode />,
  cppIcon: <FaLaptopCode />,
  cIcon: <FaLaptopCode />,
  tailwindIcon: <FaCss3Alt />,
  viteIcon: <FaBolt />,
  vsCodeIcon: <FaLaptopCode />,
  windowsIcon: <FaWindows />,
};
